services:
  - type: web
    name: bloodbank
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_REFRESH_SECRET_KEY
        generateValue: true
      - key: LANG
        value: en_US.UTF-8
      - key: LC_ALL
        value: en_US.UTF-8
      - key: FASTAPI_AMIS_ADMIN_LANGUAGE
        value: en_US
      - key: FASTAPI_AMIS_ADMIN_LOCALE
        value: en_US
    healthCheckPath: /health
