"""Add title column to reminders table

Revision ID: cf2aa9130cdb
Revises: cb834569503b
Create Date: 2025-07-18 10:21:26.721701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2aa9130cdb'
down_revision = 'cb834569503b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
