"""add_title_column_to_reminders

Revision ID: cb834569503b
Revises: 2e3440831511
Create Date: 2025-07-18 10:12:26.164082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb834569503b'
down_revision = '2e3440831511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'title')
    # ### end Alembic commands ###
